// <auto-generated />
using System;
using Cortex.Entities;
using Cortex.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cortex_backend.Migrations
{
    [DbContext(typeof(CortexDbContext))]
    partial class CortexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "Cargo", new[] { "admin", "dono", "membro" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "Cargo", "cargo", new[] { "dono", "admin", "membro" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "Prioridade", new[] { "alta", "baixa", "media", "urgente" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "Prioridade", "prioridade", new[] { "baixa", "media", "alta", "urgente" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "Status", new[] { "atrasada", "concluida", "pendente" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "Status", "status", new[] { "pendente", "atrasada", "concluida" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "TipoEntidade", new[] { "resposta_tarefa", "tarefa", "usuario" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "TipoEntidade", "tipo_entidade", new[] { "usuario", "tarefa", "resposta_tarefa" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cortex.Entities.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("RespostaTarefaId")
                        .HasColumnType("integer");

                    b.Property<int?>("TarefaId")
                        .HasColumnType("integer");

                    b.Property<TipoEntidade>("TipoEntidade")
                        .HasColumnType("TipoEntidade");

                    b.Property<string>("UrlCaminho")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RespostaTarefaId");

                    b.HasIndex("TarefaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Anexo", (string)null);
                });

            modelBuilder.Entity("Cortex.Entities.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Equipe", (string)null);
                });

            modelBuilder.Entity("Cortex.Entities.MembroEquipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Cargo>("Cargo")
                        .HasColumnType("Cargo");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EquipeId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MembroEquipe", (string)null);
                });

            modelBuilder.Entity("Cortex.Entities.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Concluida")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TarefaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Meta", (string)null);
                });

            modelBuilder.Entity("Cortex.Entities.ResponsavelTarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TarefaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ResponsavelTarefa", (string)null);
                });

            modelBuilder.Entity("Cortex.Entities.RespostaTarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataResposta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TarefaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RespostaTarefa", (string)null);
                });

            modelBuilder.Entity("Cortex.Entities.Sugestao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("TarefaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sugestao", (string)null);
                });

            modelBuilder.Entity("Cortex.Entities.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CriadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Pontuacao")
                        .HasColumnType("integer");

                    b.Property<Prioridade>("Prioridade")
                        .HasColumnType("Prioridade");

                    b.Property<Status>("Status")
                        .HasColumnType("Status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.ToTable("Tarefa", (string)null);
                });

            modelBuilder.Entity("Cortex.Entities.TicketReporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("TarefaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TicketReporte", (string)null);
                });

            modelBuilder.Entity("Cortex.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Cortex.Entities.Anexo", b =>
                {
                    b.HasOne("Cortex.Entities.Usuario", null)
                        .WithOne("FotoPerfil")
                        .HasForeignKey("Cortex.Entities.Anexo", "Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Cortex.Entities.RespostaTarefa", "RespostaTarefa")
                        .WithMany("Anexos")
                        .HasForeignKey("RespostaTarefaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cortex.Entities.Tarefa", "Tarefa")
                        .WithMany("Anexos")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cortex.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("RespostaTarefa");

                    b.Navigation("Tarefa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Cortex.Entities.MembroEquipe", b =>
                {
                    b.HasOne("Cortex.Entities.Equipe", "Equipe")
                        .WithMany("Membros")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cortex.Entities.Usuario", "Usuario")
                        .WithMany("Equipes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Cortex.Entities.Meta", b =>
                {
                    b.HasOne("Cortex.Entities.Tarefa", "Tarefa")
                        .WithMany("Metas")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cortex.Entities.Usuario", "Usuario")
                        .WithMany("Metas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Cortex.Entities.ResponsavelTarefa", b =>
                {
                    b.HasOne("Cortex.Entities.Tarefa", "Tarefa")
                        .WithMany("ResponsaveisTarefas")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cortex.Entities.Usuario", "Usuario")
                        .WithMany("ResponsaveisTarefas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Cortex.Entities.RespostaTarefa", b =>
                {
                    b.HasOne("Cortex.Entities.Tarefa", "Tarefa")
                        .WithMany("Respostas")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cortex.Entities.Usuario", "Usuario")
                        .WithMany("Respostas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Cortex.Entities.Sugestao", b =>
                {
                    b.HasOne("Cortex.Entities.Tarefa", "Tarefa")
                        .WithMany("Sugestoes")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cortex.Entities.Usuario", "Usuario")
                        .WithMany("Sugestoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Cortex.Entities.Tarefa", b =>
                {
                    b.HasOne("Cortex.Entities.Usuario", "Criador")
                        .WithMany("TarefasCriadas")
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("Cortex.Entities.TicketReporte", b =>
                {
                    b.HasOne("Cortex.Entities.Tarefa", "Tarefa")
                        .WithMany("Tickets")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortex.Entities.Usuario", "Usuario")
                        .WithMany("Tickets")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tarefa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Cortex.Entities.Equipe", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("Cortex.Entities.RespostaTarefa", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("Cortex.Entities.Tarefa", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Metas");

                    b.Navigation("ResponsaveisTarefas");

                    b.Navigation("Respostas");

                    b.Navigation("Sugestoes");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Cortex.Entities.Usuario", b =>
                {
                    b.Navigation("Equipes");

                    b.Navigation("FotoPerfil");

                    b.Navigation("Metas");

                    b.Navigation("ResponsaveisTarefas");

                    b.Navigation("Respostas");

                    b.Navigation("Sugestoes");

                    b.Navigation("TarefasCriadas");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
